name: Pubs tests

on: [push, pull_request]

jobs:
  unit-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
      - name: Test with pytest (mock API mode)
        env:
          PUBS_TESTS_MODE: MOCK
        run: pytest
      - name: Test with pytest (online API mode)
        env:
          PUBS_TESTS_MODE: COLLECT
        run: pytest
